func collectMoveAndToggleSwitch(){
    collectGem()
    moveForward()
    toggleSwitch()
}

moveForward()
collectMoveAndToggleSwitch()
moveForward()
turnLeft()
moveForward()
collectMoveAndToggleSwitch()
moveForward()
moveForward()
turnLeft()
moveForward()
collectMoveAndToggleSwitch()
moveForward()
turnLeft()
moveForward()
abc()
